language: go

go:
  - 1.5
  - 1.6
  - 1.7

os:
  - linux
  - osx

install:
  - go get github.com/smartystreets/goconvey/convey
  - go get github.com/mistralmail/mistralmail/log
  - go get github.com/mistralmail/mistralmail/helpers

script:
  - go test -v ./...
